### PR TITLE
Update for ue 4.27

### PR DESCRIPTION
**Pull request by Prikalel**
Please, before testing the plugin make sure that your device work perfectly with other apps such as [BLE scanner](https://play.google.com/store/apps/details?id=com.macdom.ble.blescanner&hl=ru&gl=US) or [LightBlue](https://play.google.com/store/apps/details?id=com.punchthrough.lightblueexplorer&hl=ru&gl=US). Also **your geolocation must be turned on** otherwise you won't be able to scan any devices.

List of changes:

1. _BluetoothSupport.uplugin_ - Updates versions and removed Docs url because it don't work.
2. _README.md_ - added Change log.
3. _Source/BluetoothSupport/BluetoothSupport.Build.cs_ -  fix tabs & add PrivateIncludePathModuleNames, 
4. _Source/BluetoothSupport/Private/Android/AndroidGateway.cpp_ - fix tabs & add correct strings workflow & add some extra DeleteRefs in JNI & add implementation of printDebugUEMessage (this function now can be called from java to print on screen).
5. _Source/BluetoothSupport/Private/Android/AndroidGateway.h_ - remove unneccessary static field (NativeBluetoothDeviceClass).
6. _Source/BluetoothSupport/Private/BluetoothSupport.cpp_ & _Source/BluetoothSupport/Private/BluetoothSupport.h_ & _Source/BluetoothSupport/Private/BluetoothSupportBPLibrary.cpp_ & _Source/BluetoothSupport/Private/ScanCallbackBase.cpp_ & _Source/BluetoothSupport/Public/Blueprint/BluetoothAdapter.cpp_- fix comments.
7. _Source/BluetoothSupport/Public/Blueprint/BluetoothAdapter.h_ - fix comments, make pure functions `IsEnabled()` and `IsLowEnergySupported()`.
8. _Source/BluetoothSupport/Public/Blueprint/BluetoothDevice.cpp_ and header - I made Get-functions `FORCEINLINE` and moved their implementation to header file.
9. _Source/BluetoothSupport/Public/ScanDevicesCallback.h_ - move `FString searchService; FString searchAddress; int32 searchTimeout;` variables to be priavte of the UScanDevicesCallback class. So in _Source/BluetoothSupport/Private/ScanDevicesCallback.cpp_ you can set them in `UScanDevicesCallback::ScanNearbyDevices` and get values in `UScanDevicesCallback::Activete_imp()` (the function `Activete_imp()` will be deleted in future commits).

**Changes in** _Source/BluetoothSupport/TaModuleAPL.xml_ :

1. Added `proguardAdditions`.
2. Removed unneeded `import android.util.Log;`, fixed `annotations.RequireApi` import.
3. Actually some other imports now can be removed such as `android.os.HandlerThread; import android.os.Bundle;`
4. Fixed comments.
5. All code blocks are now in `<![CDATA[` so xml parser won't touch them (and you don't need to write `&quot;` and others).
6. Removed `startHandlerThread` because now you can just `handler = new Handler();` and all will work.
7. Added `stopLEScan();` onDestroy additions.
8. Remove `private HandlerThread mHandlerThread = null;`.
9. Added new c++ native function for printing to screen.
10. `isBluetoothEnabled()` now will return false if `taBletoothAdapter == null` .
11. In `enableBluetooth()` there was condition `taBluetoothAdapter == null || !taBluetoothAdapter.isEnabled()` which I changed to `( taBluetoothAdapter != null && !taBluetoothAdapter.isEnabled() )` because if `taBluetoothAdapter == null` then device don't have Bluetooth at all so there is no need to turn Bluetooth on.
12. `startFilteredScan` now allow both uuid and mac address specified.
13. I made some changes in threads manipulations (see issue https://github.com/tahaHichri/UE-Bluetooth-Support/issues/9#issue-1103310749 ).
14. `connectGattDevice` won't be called from anywhere but I wrapped it so it won't do anything if `isBluetoothEnabled() is false`.
15. I changed default values of `CBluetoothDevice` class, so you can easily understand if api level is lower than 26 (as mentioned in [android documentation](https://developer.android.com/reference/android/bluetooth/le/ScanResult#constants_1) `PeriodicAdvertisingInterval` valid range is 6 (7.5ms) to 65536 (81918.75ms). And `TxPower` valid range is [-127, 126] ).

### CODE REVIEW

**Comment by Prikalel** [comment]
Also I found that `ScanCallbackBase` is used only as parent for `ScanDevicesCallback` so I merged them in one class.

**Comment by Prikalel** [comment]
See https://github.com/tahaHichri/UE-Bluetooth-Support/pull/10/commits/fc8cd7dfd6886c5f930b32ae2f4f24e19aee0201 commit message for updates.

I gonna add some extra functionality:

- [x] Controlling of `.setReportDelay(1000)` parameter,
- [x] Add request permission `ACCESS_FINE_LOCATION` and functions to check [if Geolocation is turned on](https://stackoverflow.com/questions/10311834/how-to-check-if-location-services-are-enabled).
- [x] Update README to mention, which permissions are needed, how to enable them and how to check that all settings are correct.

_See my develop branch for updates. Current tasks:_

- [x] Get this device name & MAC-address.
- [x] Add documentation for BP functions. + write some into README.
- [ ] Add GATT client.
- [ ] Create common-Bluetooth interface analogs so BP-developer can access both classic Bluetooth and BLE.

_But I don't promise anything._

**Comment by Prikalel** [comment]
Why do we need geolocation?
See [this russian discussion](https://habr.com/ru/post/536392/comments/#comment_22587614).

**Comment by tahaHichri** [comment]
Thank you for the pull request and sorry for taking too much time to merge it. I will review and merge it as soon as I can :)

**Comment by Prikalel** [comment]
@tahaHichri thank you for replying!
Please, don't hurry, I gonna add gatt service for transfer data that might be good for creating Bluetooth multiplayers.
Also if you have any questions and if I need to fix/refactor something - just write it I will fix it as soon as possible.

**Comment by Prikalel** [comment]
Please, don't hurry, I gonna add gatt service for transfer data that might be good for creating Bluetooth multiplayers.
Also if you have any questions and if I need to fix/refactor something - just write it I will fix it as soon as possible.

**Comment by Prikalel** [comment]
Currently now I'm working on the GATT server & client.
I added a lot of new functions already (see https://github.com/Prikalel/UE-Bluetooth-Support/tree/develop branch).
Still fixing it for stable work. The progress can be found here:
https://github.com/Prikalel/UE-Bluetooth-Support/projects/1
There were so many modifications so I decided to make comment messages a little bit less extensive, sorry for that.
I'll tell, when my code will be fully ready for merging.

**Comment by Prikalel** [comment]
Will reopen it when my code become ready for review.

**Pull request closed without merging**
